name: boomwheel
description: Spin to earn crypto rewards
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.9
  google_mobile_ads: ^3.0.0

flutter:
  uses-material-design: true
